const StoreAction = {
  // global
  SET_START_DATA: "SET_START_DATA",
  // student
  READ_ALL_STUDENTS_START: "READ_ALL_STUDENTS_START",
  READ_ALL_STUDENTS: "READ_ALL_STUDENTS",
  READ_ALL_MARKS: "READ_ALL_MARKS",
  SET_CREATE_MARK_DIALOG_VISIBILITY: "SET_CREATE_MARK_DIALOG_VISIBILITY",
}

export default StoreAction;